version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: aws-sdk
    versions:
    - 2.835.0
    - 2.889.0
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/cheerio"
    versions:
    - 0.22.23
    - 0.22.24
    - 0.22.25
    - 0.22.26
    - 0.22.27
