name: "Gerald the discord bot"
description: "Scrapes gg.deals for free games and posts to discord"
version: "1.0.0"
slug: "gerald_the_discord_bot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/SparrowBrain/gerald-the-discord-bot"
options:
  DiscordBotToken: "ABC"
  FetchInterval: 3600000
  FetchIntervalRandom: 900000
schema:
  DiscordBotToken: str
  FetchInterval: int
  FetchIntervalRandom: int
