name: Auto-merge
on:
  schedule:
    - cron: "0 12 * * *"
jobs:
  test:
    name: Auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: "${{ secrets.LITTLE_BUDDY_APP_ID }}"
          private_key: "${{ secrets.LITTLE_BUDDY_PRIVATE_KEY }}"

      - uses: koj-co/dependabot-pr-action@v1.1.12
        with:
          token: ${{ steps.generate_token.outputs.token }}
          merge-major: true
          merge-minor: true
          merge-patch: true
