name: Auto-test dependabot PR
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: "${{ secrets.LITTLE_BUDDY_APP_ID }}"
          private_key: "${{ secrets.LITTLE_BUDDY_PRIVATE_KEY }}"

      - name: Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pullRequests = await github.rest.pulls.list({ 
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open" 
            });

            core.info(context.repo.owner);
            core.info(context.repo.repo);

            core.info(pullRequests.data[0]);

            const dependabotPR = pullRequests.data.find((pr) => pr.user.login === "dependabot[bot]");
            if(dependabotPR === undefined){
              core.info("No dependabot PRs found. Stopping");
              return;
            }

            core.info(`Found PR: ${dependabotPR.url}`);

            // Truncate the body to keep the size of the payload under the max
            if (dependabotPR.body) {
              dependabotPR.body = dependabotPR.body.slice(0, 1000)
            }

            let clientPayload;
            clientPayload['pull_request'] = dependabotPR

            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: ok-to-test-command,
              client_payload: clientPayload,
            });
