# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env: 
        FILE_NAME: ".env"
        FILE_DATA: "DISCORD_BOT_TOKEN =  ${{ secrets.DISCORD_BOT_TOKEN }}"

    
    - run: mkdir build-zip
    - name: Generate deployment package
      run: zip -r build-zip/build.zip * -x src/\* build-zip/\*
    
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: build-zip
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test

