name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build

    - run: mkdir build-zip
    - name: Generate deployment package
      run: zip -r build-zip/build.zip * -x src/\* build-zip/\*
    
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build-zip
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - run: 'echo "DISCORD_BOT_TOKEN = $DISCORD_BOT_TOKEN" > .env'
  #     shell: bash
  #     env:
  #       DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

  #   - run: zip -ur build-zip/build.zip .env
    