name: Pull Request

on:
  pull_request:
    branches: [master]

concurrency: discord_api

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
      SCRAPE_URL: http://localhost:8090
      FETCH_INTERVAL: 1000
      HEALTH_ENDPOINT_PORT: 3050

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npm start & npx wait-on -t 60000 http://localhost:${{ env.$HEALTH_ENDPOINT_PORT }}/health
      - run: npm test
